/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthUserinfoRouteImport } from './routes/oauth/userinfo'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthProfileRouteImport } from './routes/oauth/profile'
import { Route as OauthCompleteRouteImport } from './routes/oauth/complete'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthUserinfoRoute = OauthUserinfoRouteImport.update({
  id: '/oauth/userinfo',
  path: '/oauth/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProfileRoute = OauthProfileRouteImport.update({
  id: '/oauth/profile',
  path: '/oauth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCompleteRoute = OauthCompleteRouteImport.update({
  id: '/oauth/complete',
  path: '/oauth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/resumes'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/resumes'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/authenticated'
    | '/_authenticated/resumes'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthCompleteRoute: typeof OauthCompleteRoute
  OauthProfileRoute: typeof OauthProfileRoute
  OauthTokenRoute: typeof OauthTokenRoute
  OauthUserinfoRoute: typeof OauthUserinfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/userinfo': {
      id: '/oauth/userinfo'
      path: '/oauth/userinfo'
      fullPath: '/oauth/userinfo'
      preLoaderRoute: typeof OauthUserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/profile': {
      id: '/oauth/profile'
      path: '/oauth/profile'
      fullPath: '/oauth/profile'
      preLoaderRoute: typeof OauthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/complete': {
      id: '/oauth/complete'
      path: '/oauth/complete'
      fullPath: '/oauth/complete'
      preLoaderRoute: typeof OauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthCompleteRoute: OauthCompleteRoute,
  OauthProfileRoute: OauthProfileRoute,
  OauthTokenRoute: OauthTokenRoute,
  OauthUserinfoRoute: OauthUserinfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
