/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthUserinfoRouteImport } from './routes/oauth/userinfo'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthProfileRouteImport } from './routes/oauth/profile'
import { Route as OauthCompleteRouteImport } from './routes/oauth/complete'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as EmployerSetupRouteImport } from './routes/employer/setup'
import { Route as EmployerCandidatesRouteImport } from './routes/employer/candidates'
import { Route as ApplyJobIdRouteImport } from './routes/apply/$jobId'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'

const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthUserinfoRoute = OauthUserinfoRouteImport.update({
  id: '/oauth/userinfo',
  path: '/oauth/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProfileRoute = OauthProfileRouteImport.update({
  id: '/oauth/profile',
  path: '/oauth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCompleteRoute = OauthCompleteRouteImport.update({
  id: '/oauth/complete',
  path: '/oauth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSetupRoute = EmployerSetupRouteImport.update({
  id: '/employer/setup',
  path: '/employer/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/sms-terms': typeof SmsTermsRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/setup': typeof EmployerSetupRoute
  '/join/$code': typeof JoinCodeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/sms-terms': typeof SmsTermsRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/setup': typeof EmployerSetupRoute
  '/join/$code': typeof JoinCodeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/sms-terms': typeof SmsTermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/setup': typeof EmployerSetupRoute
  '/join/$code': typeof JoinCodeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/oauth/profile': typeof OauthProfileRoute
  '/oauth/token': typeof OauthTokenRoute
  '/oauth/userinfo': typeof OauthUserinfoRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/sms-terms'
    | '/authenticated'
    | '/invite'
    | '/resumes'
    | '/apply/$jobId'
    | '/employer/candidates'
    | '/employer/setup'
    | '/join/$code'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/sms-terms'
    | '/authenticated'
    | '/invite'
    | '/resumes'
    | '/apply/$jobId'
    | '/employer/candidates'
    | '/employer/setup'
    | '/join/$code'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/sms-terms'
    | '/_authenticated/_admin'
    | '/_authenticated/authenticated'
    | '/_authenticated/invite'
    | '/_authenticated/resumes'
    | '/apply/$jobId'
    | '/employer/candidates'
    | '/employer/setup'
    | '/join/$code'
    | '/oauth/authorize'
    | '/oauth/callback'
    | '/oauth/complete'
    | '/oauth/profile'
    | '/oauth/token'
    | '/oauth/userinfo'
    | '/_authenticated/_admin/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SmsTermsRoute: typeof SmsTermsRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerSetupRoute: typeof EmployerSetupRoute
  JoinCodeRoute: typeof JoinCodeRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthCompleteRoute: typeof OauthCompleteRoute
  OauthProfileRoute: typeof OauthProfileRoute
  OauthTokenRoute: typeof OauthTokenRoute
  OauthUserinfoRoute: typeof OauthUserinfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/userinfo': {
      id: '/oauth/userinfo'
      path: '/oauth/userinfo'
      fullPath: '/oauth/userinfo'
      preLoaderRoute: typeof OauthUserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/profile': {
      id: '/oauth/profile'
      path: '/oauth/profile'
      fullPath: '/oauth/profile'
      preLoaderRoute: typeof OauthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/complete': {
      id: '/oauth/complete'
      path: '/oauth/complete'
      fullPath: '/oauth/complete'
      preLoaderRoute: typeof OauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/setup': {
      id: '/employer/setup'
      path: '/employer/setup'
      fullPath: '/employer/setup'
      preLoaderRoute: typeof EmployerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SmsTermsRoute: SmsTermsRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerSetupRoute: EmployerSetupRoute,
  JoinCodeRoute: JoinCodeRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthCompleteRoute: OauthCompleteRoute,
  OauthProfileRoute: OauthProfileRoute,
  OauthTokenRoute: OauthTokenRoute,
  OauthUserinfoRoute: OauthUserinfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
